version: '3.7'

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: zespol
      MONGO_INITDB_ROOT_PASSWORD: projektzespolowy
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  hotseat-backend:
    image: hotseat-backend
    build: ../Backend/hello-world
    ports:
      - 50000:50000
    depends_on:
      - mongodb_container
    volumes:
      - ../Backend/hello-world:/usr/src/hotseat-backend


volumes:
  mongodb_data_container:
